---
apiVersion: v2
description: "A community-supported supercharged version of paperless with an included ftp server: scan, index and archive all your physical documents."
name: paperless-ngx
type: application
home: https://github.com/signed-log/helm-paperless-ngx
icon: https://avatars.githubusercontent.com/u/99562962?s=48&v=4
version: 1.0.0-a1
# renovate: image=paperlessngx/paperless-ngx
appVersion: "2.17.1"
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: signed-log
    email: stigpro@outlook.fr
sources:
  - https://github.com/paperless-ngx/paperless-ngx
  - https://github.com/CrystalNET-org/helm-paperless-ngx
  - https://github.com/signed-log/helm-paperless-ngx
dependencies:
  - name: redis
    version: ~21.2.9
    repository: https://charts.bitnami.com/bitnami
    alias: redis
    condition: redis.enabled
  - name: mariadb
    version: ~21.0.2
    repository: https://charts.bitnami.com/bitnami
    alias: mariadb
    condition: mariadb.enabled
  - name: postgresql
    version: ~16.7.16
    repository: https://charts.bitnami.com/bitnami
    alias: postgresql
    condition: postgresql.enabled
