name: Publish Helm Chart to OCI (Manual)

on: [ "release" ]

jobs:
  publish-chart:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checkout your repository code

      - name: Install go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: '1.24'
          check-latest: true

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        id: helm-setup

      - name: Install helm docs
        run: |
          go install github.com/norwoodj/helm-docs@latest
          helm-docs --version

      - name: Prepare for packaging
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
          helm dependencies update chart

      - name: Generate Helm documentation
        run: |
          helm-docs --chart-search-root=chart --template-files=README.md.gotmpl

      - name: Package Helm Chart
        run: |
          helm package chart
        # Package the Helm chart into a .tgz file.
        # The output file will be named e.g., 'my-chart-1.0.0.tgz'.

      - name: Push Helm Chart to OCI Registry
        env:
          REPOSITORY_NAME: ${{ github.event.repository.name }}
        run: |
          # Ensure the Helm chart is packaged before pushing
          echo  ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io --username "$GITHUB_ACTOR" --password-stdin
          HELM_CHART_FILE="${CHART_NAME}-${CHART_VERSION}.tgz"
          TARGET_OCI_URI="oci://ghcr.io/${GITHUB_REPOSITORY}/${CHART_NAME}:${GITHUB_REF_NAME}"
          helm push "$HELM_CHART_FILE" "$TARGET_OCI_URI"
          echo "Successfully pushed $HELM_CHART_FILE to $TARGET_OCI_URI"
