name: Helm Chart CI

on:
  push:
    branches:
      - main # Equivalent to ${CI_REPO_DEFAULT_BRANCH} assuming 'main' is your default branch
    tags:
      - '*' # Equivalent to 'event: tag' for any tag push
  pull_request: # Equivalent to 'event: pull_request'

jobs:
  lint-chart:
    runs-on: ubuntu-latest # Standard GitHub Actions runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checkout your repository code

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        id: helm-setup

      - name: Update Helm dependencies
        run: helm dependencies update chart # Assumes your chart is in a directory named 'chart'

      - name: Lint Helm chart
        run: helm lint --with-subcharts chart # Lints the chart, including subcharts

  test-chart:
    runs-on: ubuntu-latest # Standard GitHub Actions runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for 'ct' to compare against the base branch history

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13' # Use the latest Python version

      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.12.0

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }}
